const HOSTING_DATA = [
  { Platform: "Aternos", Tier: "Free", "Harga (USD/mo)": 0, "RAM (GB)": 2, "Storage (GB)": 5, "Slot Pemain": 20, "Uptime (%)": 85, vCPU: 1, url: "https://aternos.org/" },
  { Platform: "Minefort", Tier: "Free", "Harga (USD/mo)": 0, "RAM (GB)": 2, "Storage (GB)": 5, "Slot Pemain": 20, "Uptime (%)": 82, vCPU: 1, url: "https://minefort.com/" },
  { Platform: "Server.pro", Tier: "Free", "Harga (USD/mo)": 0, "RAM (GB)": 2, "Storage (GB)": 10, "Slot Pemain": 10, "Uptime (%)": 80, vCPU: 1, url: "https://server.pro/pricing" },
  { Platform: "FalixNodes", Tier: "Free", "Harga (USD/mo)": 0, "RAM (GB)": 1, "Storage (GB)": 5, "Slot Pemain": 8, "Uptime (%)": 78, vCPU: 1, url: "https://falixnodes.net/" },
  { Platform: "ScalaCube", Tier: "Free", "Harga (USD/mo)": 0, "RAM (GB)": 1, "Storage (GB)": 8, "Slot Pemain": 10, "Uptime (%)": 80, vCPU: 1, url: "https://scalacube.com/" },
  { Platform: "Minefort", Tier: "Paid", "Harga (USD/mo)": 4.99, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 40, "Uptime (%)": 90, vCPU: 2, url: "https://minefort.com/" },
  { Platform: "Server.pro", Tier: "Premium+", "Harga (USD/mo)": 5.99, "RAM (GB)": 3, "Storage (GB)": 20, "Slot Pemain": 20, "Uptime (%)": 92, vCPU: 2, url: "https://server.pro/pricing" },
  { Platform: "Server.pro", Tier: "Extreme", "Harga (USD/mo)": 11.99, "RAM (GB)": 6, "Storage (GB)": 40, "Slot Pemain": 40, "Uptime (%)": 95, vCPU: 3, url: "https://server.pro/pricing" },
  { Platform: "Shockbyte", Tier: "Dirt", "Harga (USD/mo)": 2.50, "RAM (GB)": 1, "Storage (GB)": 10, "Slot Pemain": 20, "Uptime (%)": 99.5, vCPU: 1, url: "https://shockbyte.com" },
  { Platform: "Shockbyte", Tier: "Stone", "Harga (USD/mo)": 5.00, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.5, vCPU: 1, url: "https://shockbyte.com" },
  { Platform: "Shockbyte", Tier: "Iron", "Harga (USD/mo)": 10.00, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 80, "Uptime (%)": 99.5, vCPU: 2, url: "https://shockbyte.com" },
  { Platform: "Shockbyte", Tier: "Gold", "Harga (USD/mo)": 20.00, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 160, "Uptime (%)": 99.5, vCPU: 2, url: "https://shockbyte.com" },
  { Platform: "Shockbyte", Tier: "Titan", "Harga (USD/mo)": 40.00, "RAM (GB)": 16, "Storage (GB)": 160, "Slot Pemain": 320, "Uptime (%)": 99.5, vCPU: 4, url: "https://shockbyte.com" },
  { Platform: "BisectHosting", Tier: "Budget", "Harga (USD/mo)": 2.99, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 2, url: "https://www.bisecthosting.com/minecraft-server-hosting" },
  { Platform: "BisectHosting", Tier: "Premium4GB", "Harga (USD/mo)": 9.99, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 2, url: "https://www.bisecthosting.com/minecraft-server-hosting" },
  { Platform: "BisectHosting", Tier: "Premium8GB", "Harga (USD/mo)": 18.99, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 4, url: "https://www.bisecthosting.com/minecraft-server-hosting" },
  { Platform: "BisectHosting", Tier: "Premium16GB", "Harga (USD/mo)": 35.99, "RAM (GB)": 16, "Storage (GB)": 160, "Slot Pemain": 320, "Uptime (%)": 99.9, vCPU: 4, url: "https://www.bisecthosting.com/minecraft-server-hosting" },
  { Platform: "PebbleHost", Tier: "Basic", "Harga (USD/mo)": 3.00, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.7, vCPU: 2, url: "https://pebblehost.com" },
  { Platform: "PebbleHost", Tier: "Standard", "Harga (USD/mo)": 6.00, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 80, "Uptime (%)": 99.7, vCPU: 2, url: "https://pebblehost.com" },
  { Platform: "PebbleHost", Tier: "Pro", "Harga (USD/mo)": 12.00, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 160, "Uptime (%)": 99.7, vCPU: 4, url: "https://pebblehost.com" },
  { Platform: "PebbleHost", Tier: "Elite", "Harga (USD/mo)": 24.00, "RAM (GB)": 16, "Storage (GB)": 160, "Slot Pemain": 320, "Uptime (%)": 99.7, vCPU: 4, url: "https://pebblehost.com" },
  { Platform: "ScalaCube", Tier: "Entry", "Harga (USD/mo)": 2.50, "RAM (GB)": 1, "Storage (GB)": 20, "Slot Pemain": 20, "Uptime (%)": 99.99, vCPU: 1, url: "https://scalacube.com/" },
  { Platform: "ScalaCube", Tier: "Small", "Harga (USD/mo)": 4.99, "RAM (GB)": 2, "Storage (GB)": 40, "Slot Pemain": 40, "Uptime (%)": 99.99, vCPU: 1, url: "https://scalacube.com/" },
  { Platform: "ScalaCube", Tier: "Medium", "Harga (USD/mo)": 19.99, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 80, "Uptime (%)": 99.99, vCPU: 2, url: "https://scalacube.com/" },
  { Platform: "ScalaCube", Tier: "Large", "Harga (USD/mo)": 39.99, "RAM (GB)": 16, "Storage (GB)": 120, "Slot Pemain": 120, "Uptime (%)": 99.99, vCPU: 4, url: "https://scalacube.com/" },
  { Platform: "ScalaCube", Tier: "XL", "Harga (USD/mo)": 79.99, "RAM (GB)": 32, "Storage (GB)": 200, "Slot Pemain": 200, "Uptime (%)": 99.99, vCPU: 8, url: "https://scalacube.com/" },
  { Platform: "Apex Hosting", Tier: "Basic", "Harga (USD/mo)": 7.49, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 2, url: "https://apexminecrafthosting.com/pricing/" },
  { Platform: "Apex Hosting", Tier: "Standard", "Harga (USD/mo)": 14.99, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 2, url: "https://apexminecrafthosting.com/pricing/" },
  { Platform: "Apex Hosting", Tier: "Pro", "Harga (USD/mo)": 29.99, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 4, url: "https://apexminecrafthosting.com/pricing/" },
  { Platform: "Apex Hosting", Tier: "Elite", "Harga (USD/mo)": 59.99, "RAM (GB)": 16, "Storage (GB)": 160, "Slot Pemain": 320, "Uptime (%)": 99.9, vCPU: 4, url: "https://apexminecrafthosting.com/pricing/" },
  { Platform: "MCProHosting", Tier: "Dirt", "Harga (USD/mo)": 5.99, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 2, url: "https://www.mcprohosting.com/pricing" },
  { Platform: "MCProHosting", Tier: "Stone", "Harga (USD/mo)": 11.99, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 2, url: "https://www.mcprohosting.com/pricing" },
  { Platform: "MCProHosting", Tier: "Iron", "Harga (USD/mo)": 23.99, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 4, url: "https://www.mcprohosting.com/pricing" },
  { Platform: "MCProHosting", Tier: "Gold", "Harga (USD/mo)": 47.99, "RAM (GB)": 16, "Storage (GB)": 160, "Slot Pemain": 320, "Uptime (%)": 99.9, vCPU: 4, url: "https://www.mcprohosting.com/pricing" },
  { Platform: "Sparked Host", Tier: "Basic", "Harga (USD/mo)": 1.00, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 1, url: "https://sparkedhost.com/minecraft-server-hosting" },
  { Platform: "Sparked Host", Tier: "Standard", "Harga (USD/mo)": 6.00, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 2, url: "https://sparkedhost.com/minecraft-server-hosting" },
  { Platform: "Sparked Host", Tier: "Pro", "Harga (USD/mo)": 12.00, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 4, url: "https://sparkedhost.com/minecraft-server-hosting" },
  { Platform: "Sparked Host", Tier: "Elite", "Harga (USD/mo)": 24.00, "RAM (GB)": 16, "Storage (GB)": 160, "Slot Pemain": 320, "Uptime (%)": 99.9, vCPU: 4, url: "https://sparkedhost.com/minecraft-server-hosting" },
  { Platform: "Hostinger", Tier: "Panel1", "Harga (USD/mo)": 6.99, "RAM (GB)": 4, "Storage (GB)": 50, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 1, url: "https://hostinger.com/minecraft-server-hosting" },
  { Platform: "Hostinger", Tier: "Panel2", "Harga (USD/mo)": 9.49, "RAM (GB)": 8, "Storage (GB)": 100, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 2, url: "https://hostinger.com/minecraft-server-hosting" },
  { Platform: "Hostinger", Tier: "Panel4", "Harga (USD/mo)": 13.99, "RAM (GB)": 16, "Storage (GB)": 200, "Slot Pemain": 320, "Uptime (%)": 99.9, vCPU: 4, url: "https://hostinger.com/minecraft-server-hosting" },
  { Platform: "Hostinger", Tier: "Panel8", "Harga (USD/mo)": 27.99, "RAM (GB)": 32, "Storage (GB)": 400, "Slot Pemain": 640, "Uptime (%)": 99.9, vCPU: 8, url: "https://hostinger.com/minecraft-server-hosting" },
  { Platform: "Nodecraft", Tier: "Lite2GB", "Harga (USD/mo)": 5.96, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 1, url: "https://nodecraft.com/pricing" },
  { Platform: "Nodecraft", Tier: "Lite4GB", "Harga (USD/mo)": 11.92, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 1, url: "https://nodecraft.com/pricing" },
  { Platform: "Nodecraft", Tier: "Lite8GB", "Harga (USD/mo)": 23.84, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 2, url: "https://nodecraft.com/pricing" },
  { Platform: "Nodecraft", Tier: "Lite16GB", "Harga (USD/mo)": 47.68, "RAM (GB)": 16, "Storage (GB)": 160, "Slot Pemain": 320, "Uptime (%)": 99.9, vCPU: 4, url: "https://nodecraft.com/pricing" },
  { Platform: "Nodecraft", Tier: "Prem2GB", "Harga (USD/mo)": 9.98, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 1, url: "https://nodecraft.com/pricing" },
  { Platform: "Nodecraft", Tier: "Prem4GB", "Harga (USD/mo)": 19.98, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 2, url: "https://nodecraft.com/pricing" },
  { Platform: "Nodecraft", Tier: "Prem8GB", "Harga (USD/mo)": 39.98, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 4, url: "https://nodecraft.com/pricing" },
  { Platform: "Nodecraft", Tier: "Prem16GB", "Harga (USD/mo)": 79.98, "RAM (GB)": 16, "Storage (GB)": 160, "Slot Pemain": 320, "Uptime (%)": 99.9, vCPU: 4, url: "https://nodecraft.com/pricing" },
  { Platform: "GGServers", Tier: "Basic", "Harga (USD/mo)": 3.00, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 12, "Uptime (%)": 99.9, vCPU: 1, url: "https://www.ggservers.com" },
  { Platform: "GGServers", Tier: "Standard", "Harga (USD/mo)": 6.00, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 24, "Uptime (%)": 99.9, vCPU: 2, url: "https://www.ggservers.com" },
  { Platform: "GGServers", Tier: "Premium", "Harga (USD/mo)": 12.00, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 48, "Uptime (%)": 99.9, vCPU: 4, url: "https://www.ggservers.com" },
  { Platform: "Akliz", Tier: "Standard", "Harga (USD/mo)": 4.50, "RAM (GB)": 2, "Storage (GB)": 30, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 1, url: "https://akliz.net" },
  { Platform: "Akliz", Tier: "Advanced", "Harga (USD/mo)": 8.50, "RAM (GB)": 4, "Storage (GB)": 60, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 2, url: "https://akliz.net" },
  { Platform: "Akliz", Tier: "Premium", "Harga (USD/mo)": 16.00, "RAM (GB)": 8, "Storage (GB)": 120, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 4, url: "https://akliz.net" },
  { Platform: "Godlike.host", Tier: "Basic", "Harga (USD/mo)": 6.39, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 2, url: "https://godlike.host" },
  { Platform: "Godlike.host", Tier: "Standard", "Harga (USD/mo)": 12.79, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 2, url: "https://godlike.host" },
  { Platform: "Godlike.host", Tier: "Pro", "Harga (USD/mo)": 25.59, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 4, url: "https://godlike.host" },
  { Platform: "Godlike.host", Tier: "Elite", "Harga (USD/mo)": 64.99, "RAM (GB)": 32, "Storage (GB)": 320, "Slot Pemain": 640, "Uptime (%)": 99.9, vCPU: 8, url: "https://godlike.host" },
  { Platform: "Host Havoc", Tier: "Basic", "Harga (USD/mo)": 4.00, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 1, url: "https://hosthavoc.com" },
  { Platform: "Host Havoc", Tier: "Standard", "Harga (USD/mo)": 8.00, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 2, url: "https://hosthavoc.com" },
  { Platform: "Host Havoc", Tier: "Advanced", "Harga (USD/mo)": 16.00, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 4, url: "https://hosthavoc.com" },
  { Platform: "ServerMiner", Tier: "Basic", "Harga (USD/mo)": 5.00, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 1, url: "https://serverminer.com" },
  { Platform: "ServerMiner", Tier: "Standard", "Harga (USD/mo)": 10.00, "RAM (GB)": 4, "Storage (GB)": 40, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 2, url: "https://serverminer.com" },
  { Platform: "ServerMiner", Tier: "Premium", "Harga (USD/mo)": 20.00, "RAM (GB)": 8, "Storage (GB)": 80, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 4, url: "https://serverminer.com" },
  { Platform: "G-Portal", Tier: "Basic", "Harga (USD/mo)": 4.85, "RAM (GB)": 2, "Storage (GB)": 30, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 1, url: "https://www.g-portal.com" },
  { Platform: "G-Portal", Tier: "Standard", "Harga (USD/mo)": 9.70, "RAM (GB)": 4, "Storage (GB)": 60, "Slot Pemain": 80, "Uptime (%)": 99.9, vCPU: 2, url: "https://www.g-portal.com" },
  { Platform: "G-Portal", Tier: "Premium", "Harga (USD/mo)": 19.40, "RAM (GB)": 8, "Storage (GB)": 120, "Slot Pemain": 160, "Uptime (%)": 99.9, vCPU: 4, url: "https://www.g-portal.com" },
  { Platform: "exaroton", Tier: "PayGo", "Harga (USD/mo)": 10.00, "RAM (GB)": 4, "Storage (GB)": 10, "Slot Pemain": 80, "Uptime (%)": 99.5, vCPU: 2, url: "https://exaroton.com/" },
  { Platform: "Pine Hosting", Tier: "Standard", "Harga (USD/mo)": 4.20, "RAM (GB)": 2, "Storage (GB)": 30, "Slot Pemain": 40, "Uptime (%)": 99.8, vCPU: 1, url: "https://pinehosting.com" },
  { Platform: "CloudNord", Tier: "Basic", "Harga (USD/mo)": 5.00, "RAM (GB)": 2, "Storage (GB)": 20, "Slot Pemain": 40, "Uptime (%)": 99.9, vCPU: 1, url: "https://cloudnord.com" }
];
